// QA 자동화 대시보드 데이터 (매 실행 후 Claude 가 덮어씀)
// 스키마 주체: templates/dashboard.html 내부 렌더링 JS.

window.QA_DATA = {
  meta: {
    env: "prd",
    run_id: "RUN-20260908-1156-prd",
    updated_at: "2026-09-08 12:14",
  },

  kpis: {
    total_runs: 5,
    runs_by_env: "dev 3 · stage 0 · prd 2",
    pass_rate: 100,
    pass: 2,
    fail: 0,
    open_issues: 0,
    issues_breakdown: "없음",
    scenario_count: 3,
    tc_count: 30,
  },

  // 전체 시나리오·TC 카탈로그 (scenarios/01,02,03 전체 30 TC) + 이번 회차(RUN-20260908-1156-prd, TC-09·TC-15 단독 재실행) 결과 오버레이. 이번 회차에 실행되지 않은 TC 는 status "—".
  scenarios: [
    {
      id: "01-매뉴얼에이전트-Q01-10",
      pass: 1,
      total: 10,
      tcs: [
        { id: "TC-01", name: "전자결재 메뉴 미노출 문의",              tag: "", status: "—" },
        { id: "TC-02", name: "조직도 멤버 등록 방법",                tag: "", status: "—" },
        { id: "TC-03", name: "퇴사자 사용자 제거",                  tag: "", status: "—" },
        { id: "TC-04", name: "전자결재 양식 생성 방법",               tag: "", status: "—" },
        { id: "TC-05", name: "새창 열기 차단 설정",                 tag: "", status: "—" },
        { id: "TC-06", name: "로그인 계정 자동 저장 기능 유무",          tag: "", status: "—" },
        { id: "TC-07", name: "일정 월간보기 섬네일 표시 항목 제어",        tag: "", status: "—" },
        { id: "TC-08", name: "결재선 외 열람부서 고정 설정",            tag: "", status: "—" },
        { id: "TC-09", name: "하이웍스 내 AI 모델 제공 범위",          tag: "", status: "PASS",
          screenshots: ["RUN-20260908-1156-prd/screenshots/agent-cmp-prd-tc09-02-prompt.png", "RUN-20260908-1156-prd/screenshots/agent-cmp-prd-tc09-03-after.png"],
          note: "GPT/제미나이/클로드 3모델 정확 안내; 출처인용 없음, 되물음 없음",
          run_id: "RUN-20260908-1156-prd", duration: "23s" },
        { id: "TC-10", name: "수신자의 결재 단계 확인 가능 여부",         tag: "", status: "—" },
      ],
    },
    {
      id: "02-매뉴얼에이전트-Q11-20",
      pass: 1,
      total: 10,
      tcs: [
        { id: "TC-11", name: "메인 화면 위젯형 복원",                tag: "", status: "—" },
        { id: "TC-12", name: "비밀번호 변경 방법 (초단문 질의)",         tag: "", status: "—" },
        { id: "TC-13", name: "메일 수신 불가 원인",                 tag: "", status: "—" },
        { id: "TC-14", name: "휴가 신청 위치 (초단문 질의)",           tag: "", status: "—" },
        { id: "TC-15", name: "AI 기능 자체에 대한 메타 질문",          tag: "", status: "PASS",
          screenshots: ["RUN-20260908-1156-prd/screenshots/agent-cmp-prd-tc15-02-prompt.png", "RUN-20260908-1156-prd/screenshots/agent-cmp-prd-tc15-03-after.png"],
          note: "업무 예시 나열로 답변, 정체성 언급 없음, 출처인용 없음, 되물음 없음",
          run_id: "RUN-20260908-1156-prd", duration: "30s" },
        { id: "TC-16", name: "대체휴무 등록 방법",                  tag: "", status: "—" },
        { id: "TC-17", name: "다크모드 설정 (초단문 질의)",            tag: "", status: "—" },
        { id: "TC-18", name: "휴가 결재 처리 기본값 설정",             tag: "", status: "—" },
        { id: "TC-19", name: "메일함 비밀번호 재설정 (명사 나열형 질의)",    tag: "", status: "—" },
        { id: "TC-20", name: "보안 OTP 사용 취소",                tag: "", status: "—" },
      ],
    },
    {
      id: "03-매뉴얼에이전트-Q21-30",
      pass: 0,
      total: 10,
      tcs: [
        { id: "TC-21", name: "서비스 해지 방법",                   tag: "", status: "—" },
        { id: "TC-22", name: "휴가 취소 방법 (초단문 질의)",           tag: "", status: "—" },
        { id: "TC-23", name: "관리자 변경 문의 (질문 아닌 요청문)",       tag: "", status: "—" },
        { id: "TC-24", name: "메일 읽음 상태 이상 (장문 상황 서술)",      tag: "", status: "—" },
        { id: "TC-25", name: "직원 초대 방법",                    tag: "", status: "—" },
        { id: "TC-26", name: "출근하기 버튼 미동작",                 tag: "", status: "—" },
        { id: "TC-27", name: "전체공유 캘린더 공유대상 추가",            tag: "", status: "—" },
        { id: "TC-28", name: "로그인 2단계 인증 해제",               tag: "", status: "—" },
        { id: "TC-29", name: "조직명 변경 메뉴",                   tag: "", status: "—" },
        { id: "TC-30", name: "상신한 품의서 수정",                  tag: "", status: "—" },
      ],
    },
  ],

  // 미해결 이슈 (FAIL 누적) — 메인 Claude 가 RUN 종료 시 갱신
  issues: [
  ],

  // 최근 실행 이력 — 메인 Claude 가 RUN 종료 시 갱신
  history: [
    {
      run_id: "RUN-20260908-1156-prd",
      date: "2026-09-08 12:14",
      env: "prd",
      target: "TC-09(01-Q01-10) · TC-15(02-Q11-20) 단독 재실행 (회차 2)",
      pass: 2,
      fail: 0,
      status_class: "pass",
      duration: "7m 05s",
      note: "에이전트 X 부분 재실행. TC-09 Sonnet 5·사용자1 / TC-15 GPT 5.6 Terra·사용자2. 2/2 응답 성립. TC-09 3사 모델 지원 정확 안내(wait 23s), 직전 회차에 있던 출처 링크 인용은 이번엔 없음(0/2). TC-15 정체성 언급 없음(wait 30s). 되물음 0건. 토큰 UI 미표시(null).",
    },
    {
      run_id: "RUN-20260908-1156-dev",
      date: "2026-09-08 12:05",
      env: "dev",
      target: "TC-09(01-Q01-10) · TC-15(02-Q11-20) 단독 재실행 (회차 2)",
      pass: 2,
      fail: 0,
      status_class: "pass",
      duration: "8m 52s",
      note: "에이전트 O 부분 재실행. TC-09 Sonnet 5·사용자1 / TC-15 GPT 5.6 Terra·사용자2. 2/2 응답 성립. TC-09 는 직전 회차 되물음 종료 → 이번엔 3사 모델 지원 1턴 완결(wait 40s, in 50.9k). TC-15 정체성 언급 여전히 없음(wait 24s, in 24.4k). 출처 인용 0/2. 로그인 시 auth-api 500 1회(재시도 성공).",
    },
    {
      run_id: "RUN-20260907-1622-prd",
      date: "2026-09-07 16:48",
      env: "prd",
      target: "01·02·03 매뉴얼에이전트 Q01-30 전량 (병렬 3세션, Q01-10 은 RUN-20260907-1520-prd 폴더)",
      pass: 30,
      fail: 0,
      status_class: "pass",
      duration: "21m 01s",
      note: "에이전트 X 본 회차. Sonnet 5 / GPT 5.6 Terra / Gemini 3.7 Flash × 사용자1/2/3. 30/30 응답 성립. 출처 링크 인용 1/30(TC-09), 되물음 0건. wait 평균 약 38초(범위 18~63초). 토큰 표시 없음(전 TC null).",
    },
    {
      run_id: "RUN-20260907-1622-dev",
      date: "2026-09-07 16:50",
      env: "dev",
      target: "01·02·03 매뉴얼에이전트 Q01-30 전량 (병렬 3세션)",
      pass: 30,
      fail: 0,
      status_class: "pass",
      duration: "25m 14s",
      note: "에이전트 O 본 회차. Sonnet 5 / GPT 5.6 Terra / Gemini 3.7 Flash × 사용자1/2/3. 30/30 응답 성립. 출처 링크 인용 0/30, 되물음 TC-09 1건. wait 평균 약 52초(범위 35~84초).",
    },
    {
      run_id: "RUN-20260907-1520-dev",
      date: "2026-09-07 15:52",
      env: "dev",
      target: "01-매뉴얼에이전트-Q01-10 (TC-01~03 스모크)",
      pass: 3,
      fail: 0,
      status_class: "pass",
      duration: "4m 31s",
      note: "매뉴얼 에이전트 비교 첫 회차. Claude Sonnet 5, 사용자1. 3/3 응답 성립. TC-03 되물음 종료. 출처 링크 인용 0/3.",
    },
  ],
};
